server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url:  jdbc.mariadb://database-1.cq7w8v7xxjsd.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220929-junho
      username: admin
      password: thdud6207!

mybatis:
  mapper-locations:
    - /mappers/*.xml
